plugins {
    id 'java-library'
    alias(pluginLibs.plugins.kotlinJvm)
    alias(pluginLibs.plugins.gradlePluginPublish)
    id 'maven-publish'
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

dependencies {
    implementation gradleApi()
    implementation(navPluginLibs.bundles.navPlugin)
    implementation project(path: ':nav-plugin-runtime')
//    implementation ("com.sleepingcat.jetpack:nav-plugin-runtime:1.0")
}

group = 'io.github.tanzhihao1qaz' // 发布到中央仓库的命名规则：前两个域名要可访问（io.github），后面的要是github的用户名
version = '1.2' //插件版本

gradlePlugin {
    website = "https://github.com/tanzhihao1qaz"
    vcsUrl = "https://github.com/tanzhihao1qaz/nav-plugin/blob/main/README.md"
    plugins {
        //navPlugin名称任意
        create('navPlugin') {
            id = 'io.github.tanzhihao1qaz.nav-plugin'
            displayName = 'nav-plugin'
            implementationClass = 'com.sleepingcat.nav_plugin.NavPlugin'
            description = 'navigation路由表生成插件'
            tags.set(['navigation', 'transform', 'gradle7.4.2'])
        }
    }
}

/*
publishing {
    repositories {
        maven {
            url = "../repo"
        }
    }
}*/
