{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.tanzhihao1qaz",
    "module": "nav-plugin",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "nav-plugin-1.0.jar",
          "url": "nav-plugin-1.0.jar",
          "size": 19082,
          "sha512": "f0619256b061ecbdb1e74f382fd7ca68562c6257b2a574d2d29b01aba8c97f414dfd135484db9b4726727cf2e2a8332651e24801739e6612d403be5601379d3a",
          "sha256": "5469bbfaa9328190e02b655f612b1b8b0425fe7f3e1ecc9030e12727746aada4",
          "sha1": "7f8e5e2a938ba58dae3ab57e0cfa8cae30c4f95f",
          "md5": "d3fa359fde370c0f3ab532736443b876"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "com.sleepingcat.jetpack",
          "module": "nav-plugin-runtime",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "nav-plugin-1.0.jar",
          "url": "nav-plugin-1.0.jar",
          "size": 19082,
          "sha512": "f0619256b061ecbdb1e74f382fd7ca68562c6257b2a574d2d29b01aba8c97f414dfd135484db9b4726727cf2e2a8332651e24801739e6612d403be5601379d3a",
          "sha256": "5469bbfaa9328190e02b655f612b1b8b0425fe7f3e1ecc9030e12727746aada4",
          "sha1": "7f8e5e2a938ba58dae3ab57e0cfa8cae30c4f95f",
          "md5": "d3fa359fde370c0f3ab532736443b876"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nav-plugin-1.0-javadoc.jar",
          "url": "nav-plugin-1.0-javadoc.jar",
          "size": 261,
          "sha512": "57d4f70e1184e29748a9930104939639318002111cc9ff8f79630c4231c803581958acc8f1706466f165444cf5e98c1583199c911c38817c3d1a08adb10e0b1d",
          "sha256": "deb038a4042ae89a21732057a7e3a64d2f2661e488249637b0c86975c3903c13",
          "sha1": "f56284c5aacd9f270c035f820995d0eeb5cce293",
          "md5": "cbda42d0cbe53111428758c6881d2778"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nav-plugin-1.0-sources.jar",
          "url": "nav-plugin-1.0-sources.jar",
          "size": 5265,
          "sha512": "91c96ee90469c461abeb1faa794eb611e2f93129cdebbfa28e87a15ef0d3508b2d3d322f134bf7e5a32e60a91f676e2ae7ee36aede8ea040a8c4e2ebec320f0e",
          "sha256": "e2ec06c4d3d733ba3f612aa4e94d4a2c7be45578a1d71238137db427d17958f4",
          "sha1": "2781e51aa51ae6de3ccf2dffb1fbe70736839bae",
          "md5": "67e012bb531b81e6f183fd9c856bb343"
        }
      ]
    }
  ]
}
