{
  "formatVersion": "1.1",
  "component": {
    "group": "com.sleepingcat.jetpack",
    "module": "nav-plugin-runtime",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nav-plugin-runtime-1.0.jar",
          "url": "nav-plugin-runtime-1.0.jar",
          "size": 4972,
          "sha512": "45ba3479b251b858eebe3cb711c8ea57d8bc4268b25de663313a7db3a01f5dc0b7a83b1aed4640b1325b61f84bc87b360e6e4925ee677c6253aa17f73bbdafde",
          "sha256": "e7f94acdc5abf2d574577474999c4b4fcaa04e592edacf800f15307f2607ebbc",
          "sha1": "ae08311e304a14e2e519de52f4fa54e0e9206867",
          "md5": "92cb452f10e4bd3aeb350e3867987069"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nav-plugin-runtime-1.0.jar",
          "url": "nav-plugin-runtime-1.0.jar",
          "size": 4972,
          "sha512": "45ba3479b251b858eebe3cb711c8ea57d8bc4268b25de663313a7db3a01f5dc0b7a83b1aed4640b1325b61f84bc87b360e6e4925ee677c6253aa17f73bbdafde",
          "sha256": "e7f94acdc5abf2d574577474999c4b4fcaa04e592edacf800f15307f2607ebbc",
          "sha1": "ae08311e304a14e2e519de52f4fa54e0e9206867",
          "md5": "92cb452f10e4bd3aeb350e3867987069"
        }
      ]
    }
  ]
}
